### ISSUE TITLE
Lerna bootstrap error package.json Version

### ISSUE THREAD

**Issue by FrankTheDevop** [colmena/colmena-starter#1]
Hey Beeman,

# Purpose
The Purpose of this Issue is to show you the error I encounter following your guide and how I solved it.

# Thanks
You are building a great system there. I can see some use cases in my projects with it.

# Steps to get the error

- Install Colmena according to "Getting Started" (https://colmena-docs.now.sh/getting-started/)
- Following "API EXTENSION" until `lerna bootstrap` (https://colmena-docs.now.sh/extensions/api-extension/)

# Environment
Mac OS Sierra 10.12.5
NPM: 3.10.9
Node: 7.2.0

# Error
lerna info version 2.0.0-rc.5
lerna info Bootstrapping 24 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna ERR! execute Error: Command failed: npm install
lerna ERR! execute npm ERR! Darwin 16.6.0
lerna ERR! execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
lerna ERR! execute npm ERR! node v7.2.0
lerna ERR! execute npm ERR! npm  v3.10.9
lerna ERR! execute npm ERR! code ETARGET
lerna ERR! execute
lerna ERR! execute npm ERR! notarget No compatible version found: @colmena/admin-ui@0.0.0
lerna ERR! execute npm ERR! notarget Valid install targets:
lerna ERR! execute npm ERR! notarget 0.2.0, 0.1.0
lerna ERR! execute npm ERR! notarget
lerna ERR! execute npm ERR! notarget This is most likely not a problem with npm itself.
lerna ERR! execute npm ERR! notarget In most cases you or one of your dependencies are requesting
lerna ERR! execute npm ERR! notarget a package version that doesn't exist.
lerna ERR! execute
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/frank-dieterstadtler/Documents/Projekte/learning/colmena/extensions/colmena-starter-master/modules/admin-starter/npm-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:103:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install
lerna ERR! execute npm ERR! Darwin 16.6.0
lerna ERR! execute npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
lerna ERR! execute npm ERR! node v7.2.0
lerna ERR! execute npm ERR! npm  v3.10.9
lerna ERR! execute npm ERR! code ETARGET
lerna ERR! execute
lerna ERR! execute npm ERR! notarget No compatible version found: @colmena/admin-ui@0.0.0
lerna ERR! execute npm ERR! notarget Valid install targets:
lerna ERR! execute npm ERR! notarget 0.2.0, 0.1.0
lerna ERR! execute npm ERR! notarget
lerna ERR! execute npm ERR! notarget This is most likely not a problem with npm itself.
lerna ERR! execute npm ERR! notarget In most cases you or one of your dependencies are requesting
lerna ERR! execute npm ERR! notarget a package version that doesn't exist.
lerna ERR! execute
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/frank-dieterstadtler/Documents/Projekte/learning/colmena/extensions/colmena-starter-master/modules/admin-starter/npm-debug.log
lerna ERR! execute
lerna ERR! execute     at Promise.all.then.arr (/usr/local/lib/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:103:7)
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '',
lerna ERR! execute   stderr: 'npm ERR! Darwin 16.6.0\nnpm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"\nnpm ERR! node v7.2.0\nnpm ERR! npm  v3.10.9\nnpm ERR! code ETARGET\n\nnpm ERR! notarget No compatible version found: @colmena/admin-ui@0.0.0\nnpm ERR! notarget Valid install targets:\nnpm ERR! notarget 0.2.0, 0.1.0\nnpm ERR! notarget \nnpm ERR! notarget This is most likely not a problem with npm itself.\nnpm ERR! notarget In most cases you or one of your dependencies are requesting\nnpm ERR! notarget a package version that doesn\'t exist.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/frank-dieterstadtler/Documents/Projekte/learning/colmena/extensions/colmena-starter-master/modules/admin-starter/npm-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm install',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
(node:9190) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: npm install
npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: @colmena/admin-ui@0.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.2.0, 0.1.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/frank-dieterstadtler/Documents/Projekte/learning/colmena/extensions/colmena-starter-master/modules/admin-starter/npm-debug.log

(node:9190) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

# My Solution
Change extensions/colmena-starter-master/modules/admin-starter/package.json admin-ui 0.0.0 to 0.2.0

Kind Regards,
Frank

**Comment by beeman** [comment]
Fixed by @SebastianPodgajny in #2
